### ISSUE TITLE
Feature Request: "Tune Quickprint" Options

### ISSUE THREAD

**Issue by dereed999** [daid/LegacyCura#312] opened 2013-01-09 13:19 UTC
The "quickprint" choices (normal, fast, high quality, thin walled) generally work very well.  But every now and then a user might want to "tune" them or add in an "add-in" (like pause).  There's no "one click" way (that I can find) to "import" a given quickprint "profile" into the "full settings".

Maybe just add some other options beyond "reset profile to default".  Maybe "reset profile to 'normal'", "reset profile to 'high quality'", ...

(As a side note I discovered that the hard way when I did a quick print and it worked well but wanted to add a pause [color change].  In "full settings" the print became more problematic.  Turns out for some reason the "quick print" options generally use 0.2mm as the first layer but the "full settings" had 0.3mm as the first layer which made it misbehave!  Took me a while to figure that one out!)

**Comment by daid** [comment] 2013-01-09 14:25
You can "copy" the quickprint settings to the normal window if you first slice something and then use the "load profile from GCode" function. Not ideal, but works.

There are some ideas on improving the dialogs and providing a better configurable interface. But there are a few other pressing issues to solve first.

**Comment by smorloc** [comment] 2013-01-26 18:30
Maybe this will help as a stopgap:

I have created Cura profiles that contain the Quickprint settings. You can basically achieve the same results as Quickprint by using this profiles. The advantage to using profiles is that you can tweak them to suit. You can find the default profiles at:

https://github.com/smorloc/CuraProfiles

Read the notes/instructions at the bottom of the page in order to tailor to your specific machine setup.

**Comment by daid** [comment] 2013-11-25 12:44
Closing as duplicate of #502

**Closed as completed by daid** 2013-11-25 12:44 UTC
