### ISSUE TITLE
Config Wizard issue

### ISSUE THREAD

**Issue by MarkBruckard** [daid/LegacyCura#1529] opened 2016-08-12 06:18 UTC
Hi.  I'm new to Cura and am running 15.04 on Linux.  I am trying to set up my Wombot 3D printer but I have run into an odd problem: The option I need is below the edge of the configuration wizard window.  I can't tab through the options, I can't resize the window, nothing.  
The Wombot instructions tell me to select "Other" at the bottom of this page, but as you can see, it is outside the limits of the window.
![curaissue](https://cloud.githubusercontent.com/assets/20984678/17614273/528ea722-60a8-11e6-99a3-6820e9a75d92.png)

**Comment by MarkBruckard** [comment] 2016-08-12 06:19
Here is what I am suppose to see.
![intended](https://cloud.githubusercontent.com/assets/20984678/17614291/84814488-60a8-11e6-9828-fddb513fc03a.png)

**Comment by MarkBruckard** [comment] 2016-08-12 06:20
Sorry, that should have been "Custom" not "Other" in my original post.

**Comment by Ghostkeeper** [comment] 2016-08-12 08:41
Duplicate of https://github.com/daid/Cura/issues/1418

**Comment by daid** [comment] 2016-08-12 10:27
As we are not planning to update the 15.04 anymore in preference for the new Cura 2.1, you'll have to use a workaround.

You can delete a bunch of machine profiles in /usr/share/cura/resources/machines to reduce this list and make the other option visible.

**Closed as completed by daid** 2016-08-12 10:27 UTC

**Comment by MarkBruckard** [comment] 2016-08-12 21:52
Thanks.  All good now.  I just put the .ini file for my printer in that folder and moved the rest into a spares folder.  works now.  thanks.
