### ISSUE TITLE
Print window layout is messed

### ISSUE THREAD

**Issue by trikko** [daid/LegacyCura#846] opened 2014-05-21 20:35 UTC
On ubuntu 14.04 + Cura 14.03  print window is messed up:
- Temperature data are covered by buttons
- If my laptop is running on battery, warning message is shown white on grey.
- Widgets are not well placed :)

![curabug](https://cloud.githubusercontent.com/assets/647157/3046296/4fe209e0-e127-11e3-9f0a-b6066568ab03.png)

**Comment by getSurreal** [comment] 2014-05-25 17:39
Same issue on OSX

**Comment by daid** [comment] 2014-05-26 09:50
Duplicate of #818

**Closed as completed by daid** 2014-05-26 09:50 UTC
