### ISSUE TITLE
serial_port always "AUTO" in printer-gui

### ISSUE THREAD

**Issue by oni303** [daid/LegacyCura#398] opened 2013-04-07 11:10 UTC
I have problems to to set the serial port. In the preferences-gui I configured /dev/ttyUSB0 but the printer-gui always tries to connect with" AUTO".

Changing monitoring state from 'Offline' to 'Detecting serial port'
Serial port list: ['/dev/ttyUSB0', 'VIRTUAL']
Connecting to: /dev/ttyUSB0
Error while connecting to /dev/ttyUSB0: 'Timeout'
Connecting to: VIRTUAL
Error while connecting to VIRTUAL: 'Failed to open serial port'
Failed to open serial port (AUTO)

It fails cause of my bootloader.
After some more debuging  I found out that the preferences-gui loads the "serial_port" correctly from the preferences but the printer-gui prints:

serial_port not found in preferences, so using default: AUTO
serial_baud not found in preferences, so using default: AUTO
serial_baud_auto not found in preferences, so using default:
serial_port_auto not found in preferences, so using default:
filament_density not found in preferences, so using default: 1300
filament_cost_kg not found in preferences, so using default: 0
filament_cost_meter not found in preferences, so using default: 0

Any idea how to fix this?

**Comment by daid** [comment] 2013-04-07 19:59
Which version are you running? As the 'VIRTUAL' option only shows when you are running development versions.

**Comment by oni303** [comment] 2013-04-08 10:41
It is the git master last commit 1505743fe179920957b5596424a86907fb7e8854 (Apr 4th)

**Comment by oni303** [comment] 2013-04-09 21:57
ok here some more details:
in baseConfig.py "print profile" leads to "module 'Cura.util.profile' from '/usr/share/cura/Cura/util/profile.pyc'"
in machineCom.py it leads to "module 'Cura.util.profile' from 'Cura/util/profile.pyc'" 
I do not know if it is a a problem but it is the only difference I was able to find until now.

**Comment by daid** [comment] 2013-04-16 12:52
There is something going wrong with the mac version and reading the preferences from some pieces of the code. Still searching for the cause.

**Comment by daid** [comment] 2013-12-12 09:46
Should be fixed in newer versions.

**Closed as completed by daid** 2013-12-12 09:46 UTC
