### ISSUE TITLE
How to change setting for "Select a print type:" in Quickprint mode?

### ISSUE THREAD

**Issue by Kenzu** [daid/LegacyCura#290] opened 2012-12-19 09:33 UTC
I have a Reprap Prusa and run setup wizard. Have changed temperature to 185C in normal mode for my PLA and prints is beautiful. But if i use "Quickprint mode", the temperature is 220C (maybe standard setting for a ultimaker?).
I will normally use "Normal mode" but my dad would love to use "Quickprint mode", because of to many settings in "Normal mode"

Jesper

**Comment by daid** [comment] 2012-12-19 09:48
There have been more requests for the ability to modify quickprint. But right now it's hard-coded in "gui/simpleMode.py", so you could modify that file for different settings.

**Comment by Kenzu** [comment] 2012-12-19 10:12
Okay, why not keep it hardcoded to some extend, but grap some settings and multiply them for each mode.
ex.:

if self.printTypeNormal.GetValue():
            put('wall_thickness', float(get('nozzle_size") \* 2.0)
            put('layer_height', '0.2')
            put('fill_density', '20')
        elif self.printTypeLow.GetValue():
            put('wall_thickness', float(get('nozzle_size") \* 1.4)
            put('layer_height', '0.25')
            put('fill_density', '10')
            put('print_speed', float(get('print_speed')) \* 1.2)
            put('cool_min_layer_time', float(get('cool_min_layer_time')) \* 0.3)
            put('bottom_layer_speed', float(get('print_speed')) \* 0.3)

I'am no expert i programming, so don't know if it's done right, but hope you understand. :-)

**Comment by daid** [comment] 2012-12-19 13:15
I do understand, but I want the quickprint to always function the same, no matter what you have configured at the normal print. (Nozzle size is a bit of an exception on that)

I could make a condition on RepRap/Ultimaker. As I think that RepRaps need lower temperature and lower speeds?

**Comment by Kenzu** [comment] 2012-12-19 13:25
I agree with you that it should function the same, but I think that nozzle size, temperature (pla and abs), speed and retraction mm, should depend on wizard or normal settings. The rest should be static static.
So maybe make a temperature setting for both PLA and ABS i normal setting should be added, and then you have them all. :-)

**Comment by daid** [comment] 2012-12-19 14:54
In all honesty, the quickprint mode was never really designed for RepRaps. Which is why Cura starts in normal mode when you have selected a RepRap in the first run wizard. While it starts with the quickprint mode for Ultimaker.

**Comment by Kenzu** [comment] 2012-12-19 14:57
okay, maybe I have to learn python then and play with it my self :-)

**Comment by dereed999** [comment] 2013-01-09 13:27
I should have read this thread before posting my feature request.  Why not "do the best of both"?  Why not have one UI?  Have "quick print" be the first, default, tab in "full settings" with a fifth option of "custom".  When you click one of the choices (let's say "high quality") the settings on all the other tabs change to match "high quality" settings?  You can then click on those other tabs and make any changes required (which would switch the "choice" to "custom")?  Also, you could consider putting temperature on the "quick print" tab since it's probably the single parameter most "tuned".

**Comment by smorloc** [comment] 2013-01-26 18:29
Maybe this will help you folks address the concerns in this issue:

I have created Cura profiles that contain the Quickprint settings.  You can basically achieve the same results as Quickprint by using this profiles.  The advantage to using profiles is that you can tweak them to suit.  You can find the default profiles at:

https://github.com/smorloc/CuraProfiles

Read the notes/instructions at the bottom of the page in order to tailor to your specific machine setup.

**Comment by Intrinsically-Sublime** [comment] 2013-01-27 00:07
I was thinking to have Quickprint look in a folder for profiles called "Normal.ini" "Fast.ini" "High.ini" "Vase.ini" when in RepRap mode. Then if it finds them it would display the name and radio box. This would allow people to open them an edit them for there machine.

**Comment by daid** [comment] 2013-11-25 12:44
Closing as duplicate of #502

**Closed as completed by daid** 2013-11-25 12:44 UTC
