### ISSUE TITLE
Cura 14.02-RC5 - Bridging infill at angle to perimeters

### ISSUE THREAD

**Issue by Itchetiky** [daid/LegacyCura#762] opened 2014-03-05 08:12 UTC
I'm not sure if it's user error, but I've sliced the STL several times and the first layer infill of the bridge is angled in relation to the perimeters.

Since this seems like a Cura slicing issue, I'm not sure if it still fits in the Cura repo or not.

I've created a repo with the STL, GCode, and screenshot showing the detail. The screenshot is the same as the attached here.

Repo: https://github.com/Itchetiky/Cura-14.02-RC5-Bridging

Screenshot -
![jonaskuehling_x_ends_threadedrod_idler_cura](https://f.cloud.github.com/assets/2300403/2330802/1a0af6c8-a43d-11e3-861d-8bee8a75093c.png)

**Comment by nallath** [comment] 2014-03-05 08:38
What was the expected behaviour? What would be the 'correct' result according to you?

**Comment by Itchetiky** [comment] 2014-03-05 09:14
I was expecting the infill to run parallel to the long edge. It appears to me that the infill is angled 45 degree's to the long edge. Traditionally the infill would be parallel.

That being said when I printed the model, the bridge did come out just fine. So I wonder if bridging is expected to print like this?

**Comment by nallath** [comment] 2014-03-05 09:30
I can remember that @daid once told me that this was expected behavior. I'll ask him to respond with a definitive answer.

**Comment by daid** [comment] 2014-03-05 10:01
Bridge detection has issues. There is an internal issue for this open. There is also a pull-request on the engine which changes this behaviour (however, due to the large amount of changes in that pull reuqest I have not merged it yet)

**Closed as completed by daid** 2014-03-05 10:01 UTC
Labels: Bug, SlicingEngine
