### ISSUE TITLE
YouMagine window/dialog cannot be closed

### ISSUE THREAD

**Issue by hroncok** [daid/LegacyCura#663] opened 2013-12-15 13:24 UTC
Steps to reproduce:
1. Remove ~/.cura
2. Share something on YouMagine
3. Do not add the token and try to close the window

Actual result: Nothing happens

Desired result: The dialog is closed

Can reproduce with current SteamEngine branch as well as with 13.11.2 and 13.10.

**Comment by daid** [comment] 2013-12-16 09:53
Mac/Windows/Linux?

**Comment by hroncok** [comment] 2013-12-16 10:01
Sorry, Linux.

**Comment by daid** [comment] 2013-12-18 13:44
Might be a linux specific problem, and could be related to #662, as I could not reproduce it on windows.

**Comment by nallath** [comment] 2014-03-03 16:30
This was fixed by me some time ago.

**Closed as completed by nallath** 2014-03-03 16:30 UTC
Labels: Bug
