### ISSUE TITLE
Wizard extrudes much less than 100mm during test extrusion

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#7] opened 2012-03-14 03:37 UTC
On my machine the first run wizard extrudes more like 25mm of filament instead of 100mm (measured by removing the bowden cable from the extruder and starting the filament level with the top of the extruder, extruding the filament, and then measuring from the top of the extruded filament down to the top of the extruder).

Using PrintRun to extrude 100mm of filament works fine.

I'm using my branch, which should be equivalent to your branch at this point in time.

**Comment by frollard** [comment] 2012-03-14 03:58
Seconded;

Except mine extrudes none.  PrintRun extrudes fine.
Symptom; all motors stay freewheeling during the wizard, when hitting 'extrude 100mm' they all lock up/energize, but none move for about 3 seconds, then they freewheel again.

Win7 64, JRE32, pypy included in package
Ultimaker 2560 board with included marlin.
SkeinPyPy beta 3

...I'm not smart enough to get Alpha4 working yet...

**Comment by RedwoodForest** [comment] 2012-03-14 04:02
@frollard Have you made sure that PrintRun is not already connected to your Ultimaker when you make the test extrusion?

There must be no active connection to your Ultimaker when you click the button for the test extrusion.

**Comment by frollard** [comment] 2012-03-14 04:41
Correct, only skeinpypy running...

**Comment by daid** [comment] 2012-03-14 12:25
The problem is in the test extrusion. It completely ignores the given "steps per E" setting. The released version also has the problem that it closes the connection to the printer before the extrusion is done, which can cause the extrusion to stop.

Both problems should be fixed now, but I'll have a good test with them before I close this.

**Comment by frollard** [comment] 2012-03-14 21:33
Sounds wonderful!

sub-section of the problem - now if the test works, that is great, but does the rest of the skeining use the number from the tests?  I found even if I changed the number manually, the output gcode still wouldn't allow the extruder to run remotely fast enough to print (about 10-20% of the required speed), regardless of the steps value.

**Comment by daid** [comment] 2012-03-15 09:53
Check the resulting GCode, there should be an M92 Exxx in the final gcode, right at the top. The number should also have been saved in the preferences.ini file.

**Comment by frollard** [comment] 2012-03-15 10:07
Current (same as I was using before) version has no M92 values anywhere in the gcode file.  Forgive my extreme ignorance; I'm new to github and python - which files should I replace to get the newest version?

;TYPE:CUSTOM
M109 S250.0
G21        ;metric values
G90        ;absolute positioning
G28 X0 Y0  ;move X/Y to min endstops
G28 Z0     ;move Z to min endstops
G92 X0 Y0 Z0 E0 ;reset software position to front/left/z=0.0
G21
G1 Z15.0 F400
G92 E0         ;zero the extruded length
G1 F75 E5
G1 E3.5
G92 E0         ;zero the extruded length again
G1 X100.0 Y100.0 F3500
G1 Z0.0 F400
G90 ;set positioning to absolute
G21 ;set units to millimeters
M105
M106
M113 S1.0
M108 S10.03
;TYPE:SKIRT
....continued.

**Comment by daid** [comment] 2012-03-15 10:17
You should replace all files in the SkeinPyPy folder. But the file that is causing this is SkeinPyPy/fabmetheus_utilities/settings.py

**Comment by frollard** [comment] 2012-03-15 10:54
BAM.

;TYPE:CUSTOM
M92 E865.888
M109 S250.0
G21        ;metric values
G90        ;absolute positioning
G28 X0 Y0  ;move X/Y to min endstops

I was 'save link as' on the files and of course that links to the page describing the changes; once I pulled the zip file and used that everything is glorious!

Now I just need a 'reasonable hour' to go to the shop where the maker is and see if it will print!  This took skeining a sphere from 6 minutes to 35 seconds!  You (and other collaborators) are truly heroes!

**Comment by frollard** [comment] 2012-03-16 05:34
So, to further the ORIGINAL issue; the bot prints correctly with the number 890ish...BUT, that still only 'test' extrudes 25mm.  To get it up to the correct length it wants a number 3000-6000, which gives a full 100mm, but then when printing it goes ape-poop and tries to extrude way faster than usual!  The wizard still needs some tweaking;

--900 extrudes about 25mm at a SLOW speed
6000 extrudes about 100 mm at FAST speed...so it's not feeding just steps, but maybe half steps and its being misinterpreted down the line.

**Comment by daid** [comment] 2012-03-16 15:39
Odd. I ask for an extrusion at 300mm/s, which should be quite fast.

The wizard does:
    M302
    M92 E[currentEValue]
    G92 E0
    G1 E100 F300
And then it waits 10 seconds and disconnects. (this disconnect most likely causes your printer to reset)
Or... how fast is 300mm/min? Not that fast really... damn. 10 seconds is not enough then. Upping the speed, and lengthen the delay should work I think.

**Comment by frollard** [comment] 2012-03-16 23:21
Good call; max it could do in that time was 50mm...

To be as clear as possible, there was a definitive SPEED difference too when I used it, it extruded for about 3-5 seconds each time.  When I up the number it extrudes for the same amount of time but it just comes out faster.

**Comment by daid** [comment] 2012-03-16 23:52
I tested this before the Beta4 release, and now it worked flawlessly for me.

**Closed as completed** 2012-03-19 10:06 UTC
Labels: Bug
