### ISSUE TITLE
Print window is crashing in the middle of all prints

### ISSUE THREAD

**Issue by shellixyz** [daid/LegacyCura#551] opened 2013-09-05 16:36 UTC
I'm testing the git version. Displayed version is 13.06.5, last pull yesterday.

This error is reproducible all the time.
In the middle of the print after some tens of thousands of lines every time the printing program crashes and obviously the printer stops.

Tested on Debian 7 and Fedora 19.

> > The program 'python' received an X Window System error.
> > This probably reflects a bug in the program.
> > The error was 'BadAlloc (insufficient resources for operation)'.
> >  (Details: serial 14314411 error_code 11 request_code 53 minor_code 0)
> >  (Note to programmers: normally, X errors are reported asynchronously;
> >   that is, you will receive the error a while after causing it.
> >   To debug your program, run it with the --sync command line
> >   option to change this behavior. You can then get a meaningful
> >   backtrace from your debugger if you break on the gdk_x_error() function.) 

I don't know if it's related but below that was:

Traceback (most recent call last):
  File "/usr/share/cura/Cura/gui/mainWindow.py", line 62, in <lambda>
    self.Bind(wx.EVT_MENU, lambda e: self.scene.showPrintWindow(), i)
  File "/usr/share/cura/Cura/gui/sceneView.py", line 200, in showPrintWindow
    self._slicer.submitSliceInfoOnline()
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 317, in submitSliceInfoOnline
    'profile': profile.getGlobalProfileString(),
AttributeError: 'module' object has no attribute 'getGlobalProfileString'
Traceback (most recent call last):
  File "/usr/share/cura/Cura/gui/mainWindow.py", line 62, in <lambda>
    self.Bind(wx.EVT_MENU, lambda e: self.scene.showPrintWindow(), i)
  File "/usr/share/cura/Cura/gui/sceneView.py", line 200, in showPrintWindow
    self._slicer.submitSliceInfoOnline()
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 317, in submitSliceInfoOnline
    'profile': profile.getGlobalProfileString(),
AttributeError: 'module' object has no attribute 'getGlobalProfileString'

**Comment by hg42** [comment] 2013-09-08 14:37
I also had this problem on three not very big prints. The last was a print of herringbone gears for my extruder. The print stopped about a mm above the center of the herringbone pattern.

The "Printing" window is closed then (I always was away from the printer, so I didn't see what happend exactly).

Spontaneously, it looks like it's always a certain amount of lines or something like that, because smaller parts printed well before.

I am running current Cura from github on linux with a current Marlin firmware from github on a Rostock variant.

I think, it's not a problem of the firmware or the generated GCODE, because the latter prints fine from Repetier-Host when exported (assuming the exported GCODE is identical to the internal representation).

I would like to run Cura in a kind of simulation mode for testing, is this possible?
Can I print without filament (ok, thinking again, the answer should be yes, I just should remove the filament).
But printing much faster would be even nicer.
Do you have another idea, how I can find the point where the printing breaks?

**Comment by hg42** [comment] 2013-09-08 15:14
when I set both temperatures to zero and switch off the power supply, I am able to run the print without moving anything. Unfortunately Cura doesn't print with the speed shown in the main window (16 min.) but something seems to cause to a slow down. So printing time is estimated to 2 hours now. I'll report later.
Btw. how can I get a log of the GCODE etc.?

**Comment by hg42** [comment] 2013-09-08 15:49
Just for information, this error:

AttributeError: 'module' object has no attribute 'getGlobalProfileString'

appears long before the crash, so it doesn't seem to be related to the crash

**Comment by hg42** [comment] 2013-09-08 16:52
The test had about 450000 lines and the crash was after 

...
Error:No Line Number with checksum, Last Line: 309782
Error:Line Number is not Last Line Number+1, Last Line: 310692
Error:checksum mismatch, Last Line: 311816
Error:No Line Number with checksum, Last Line: 311816
Error:checksum mismatch, Last Line: 313105
Error:Line Number is not Last Line Number+1, Last Line: 313105
Error:checksum mismatch, Last Line: 314528
Error:No Line Number with checksum, Last Line: 314528
[--- end of file ---]

(the file is full of such lines)

I think I saw some number above 395000 in the printing window just before the crash, but I am not sure.

I also get these lines distributed over the log:

echo:Unknown command: "7"
echo:Unknown command: "23"
echo:Unknown command: "4"
echo:Unknown command: "9"
echo:Unknown command: "09"
echo:Unknown command: "1"
echo:Unknown command: "9"
echo:Unknown command: "6"
echo:Unknown command: "108"
echo:Unknown command: "18"
echo:Unknown command: "95"
echo:Unknown command: "24"
echo:Unknown command: "108"
echo:Unknown command: "7"

The exported GCODE doesn't contain such lines starting with a number.

**Comment by hg42** [comment] 2013-09-09 16:57
well...

I made many tests with different parameters with those herringbone gears and also tested with gcode generated by a ruby script (to get a certain number of elements/lines I generated a cylinder).
With this script I managed to reproducibly trigger the problem after about 1000-1300 lines. So the very big number of lines of the gears surely isn't the reason for the "crash".
But...today the same script parameters don't crash at all (or may be I have overlooked another change in my setup).
However, the gears generated by Cura with the original parameters still stop at the same height.
So it's still very unclear, what causes the "Printing" window to stop printing and close.

Facts:
- the count of lines _does_ matter (reproducibly triggering the error in a narrow range of line numbers, but not exactly at the same line), but the range seems to be dependent on some other conditions.
- from experiments with the gears I once concluded that nothing happens when not "moving" the E value, but I have to revisit that conclusion.
- the so called "crash" doesn't leave any corresponding output in the terminal window where I started cura (under linux I usually get python output in the terminal, like the error messages mentioned above). I am unsure if it's a crash at all.

**Comment by hg42** [comment] 2013-09-09 21:20
I did another test with the gears stl, using different parameters leading to a smaller gcode file of about 125000 lines.
I used a high flow value of 500%. The Printing window disappeared.
Then I set flow to 0% and now the print finished normally.
I exported both to gcode files and compared them and indeed only the E values changed.
So the E values seem to be mandatory.

I wonder why this problem doesn't effect more people.
This lets me think, that some of my more unusual settings could cause the issue.
linux and Rostock printer come to mind.
I use moves of 150 mm/s and am currently printing with 100 mm/s.
Baudrate is 115200.
Retraction is enabled.

@shellixyz do you use retraction?

**Comment by shellixyz** [comment] 2013-09-10 20:25
Nice experimentations. I'm using retraction yes. I also tested this with different STL files. Always the same result (stopping) after what seems to be an almost equal number of lines judging from the completeness of the part.

I had the idea like you to simulate printing but my idea was to disable the extruder heater and set all the E arguments in the G-Code to 0. Unfortunately unimplemented for now as I don't really have the time.

The problem doesn't show up with the last release on windows but I should also test it on Linux as the issue seems to be linked to the Cura GUI (X error). Maybe unfreed X resources for an unknown reason.

I used print speed < 100mm/s, move speed 150mm/s, baudrate 250000
with a Bukobot (Azteeg X3 + Marlin).

**Comment by hg42** [comment] 2013-09-11 00:25
You can simply set flow to 0% then all E values are set to zero.
I also thought about this could be caused by the gui.
Another cause could be communication with the main gui.
I wondered why the yellow plane moving up while printing occurs only 2 or 3 times while printing, even when printing  a higher object like my simulated cylinder (400 mm). May be there's a queue overflow or something. But I didn't examine the source code for now, because I'm too busy.

**Comment by hg42** [comment] 2013-09-11 16:50
Currently I am getting the error _very_ early (in the first layer, without having changed anything in parameters etc., simply loading the gcode file and printing, so the configuration should be loaded from the file, right?)

When I run the printing window standalone via this script:

------------------ printing-window
#!/bin/sh
PYTHONPATH=$PYTHONPATH:/usr/share/cura/ /usr/bin/python -u -m Cura.cura -r $*

I got this output:

STATE:IDLE
STATE:IDLE
STATE:PRINTING
Z:0.100000
The program 'python' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 827222 error_code 11 request_code 53 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
./printing-window ParametricHerringboneGears-test.gcode  13.66s user 0.56s system 17% cpu 1:21.56 total

The last line is an output (timing) from my zsh.

I tried the same gcode file in current cura compiled from github and it does about the same after an equal amount of time and in the first layer:

> > The program 'python' received an X Window System error.
> > This probably reflects a bug in the program.
> > The error was 'BadAlloc (insufficient resources for operation)'.
> >  (Details: serial 786249 error_code 11 request_code 53 minor_code 0)
> >  (Note to programmers: normally, X errors are reported asynchronously;
> >   that is, you will receive the error a while after causing it.
> >   To debug your program, run it with the --sync command line
> >   option to change this behavior. You can then get a meaningful
> >   backtrace from your debugger if you break on the gdk_x_error() function.)
> > Closing down
> > VBO was not properly released!
> > VBO was not properly released!
> > VBO was not properly released!
> > [repeated many times, what's that?]

Now, how can I start the printing window in --sync mode controlled by gdb?

[EDIT] Ok, I see, this is the error shellixyz already got above...

**Comment by hg42** [comment] 2013-09-11 17:41
Suppressing those Marlin(?) error messages in the Term tab like this:

```
def mcMessage(self, message):
    pass #wx.CallAfter(self.AddTermLog, message)
```

seems to work around the problem, at least printing gets over the former "point of crash". I am currently testing with the gears gcode file with full 440000 lines, I'll report later.

---

ok, that works, so showing the error messages seems to be the problem

**Comment by daid** [comment] 2013-09-16 13:11
(back after 2 weeks of vacation)

Sounds like the textbox crashes on Linux with too much text in it. Should be easy to work around that.

**Comment by hg42** [comment] 2013-09-16 15:48
I think, the box is not very full when it crashes, the error messages come in very slow, say 1 per minute or so.
In some tests I got the crash after only 1500 lines of GCODE and very few messages in the window.
For me, it looks more like a multithreading problem.

I also wonder, why those messages occur, there seems to be a problem with the communication between Cura and Marlin ("checksum mismatch", and "unknown command" with numbers as command).
But sending the same GCODE file with e.g. RepetierHost (loading the gcode not the stl) doesn't show these messages.

I think, I should try some things like logging to a file instead of the text box, or limiting the text box to a few lines, etc., but I'm very busy currently, so don't know when I can do this.

**Comment by hg42** [comment] 2013-09-16 18:15
repeating each line 10000 times forces the crash nearly immediately

```
def AddTermLog(self, line):
    for i in xrange(1, 10000):
      self.log_lines_count += 1      #!!!
      self.termLog.AppendText(unicode(line, 'utf-8', 'replace'))
      l = len(self.termLog.GetValue())
      self.termLog.SetCaret(wx.Caret(self.termLog, (l, l)))
    print self.log_lines_count
```

instead this seems to work:

```
def AddTermLog(self, line):
    self.termLog.SetInsertionPointEnd()   # put caret at end
    for i in xrange(0, 10000):
      self.log_lines_count += 1      #!!!
      self.termLog.AppendText(unicode(line, 'utf-8', 'replace'))
    #l = self.termLog.GetLastPosition()   # more correct way to determine end pos
    #self.termLog.ShowPosition(l)              # porbably not necessary
    print self.log_lines_count
```

The main problem seems to be using wxCaret together with big values or perhaps the value is bigger than the real text (unicode vs. bytes?).

I will test this further and then prepare a pull request, ok?

**Comment by hg42** [comment] 2013-09-16 18:20
btw. this:

def AddTermLog(self, line):
    for i in xrange(1, 10000):
      self.log_lines_count += 1      #!!!
      self.termLog.AppendText(unicode(line, 'utf-8', 'replace'))
    l = len(self.termLog.GetValue())
    self.termLog.SetCaret(wx.Caret(self.termLog, (l, l)))
    print self.log_lines_count

also crashes (only one SetCaret after appending 10000 lines), so that's why I blame SetCaret.
I'm not very familiar with wx, but I read somewhere that SetCaret is for your own controls and not used in TextCtrls.

**Comment by hg42** [comment] 2013-09-16 18:37
can someone test this on other platforms:

```
def AddTermLog(self, line):
    self.termLog.SetInsertionPointEnd()
    self.termLog.AppendText(unicode(line, 'utf-8', 'replace'))
    #l = self.termLog.GetLastPosition()     # if needed (windows? mac?)
    #self.termLog.ShowPosition(l)
```

**Comment by hg42** [comment] 2013-09-16 23:23
I created a pull request...

**Comment by angasule** [comment] 2013-09-17 12:01
I tried the modifications in hg42's commit and it fixed the issue for me.

**Comment by hg42** [comment] 2013-09-17 12:36
@angasule on which OS?

**Comment by angasule** [comment] 2013-09-17 12:38
@hg42 Linux AMD64, installed from the .deb

**Comment by hg42** [comment] 2013-09-17 19:17
thanks, same here (debian).
Anyone with Windows or Mac?

**Comment by daid** [comment] 2013-09-17 21:06
Got windows here, but little time to test (stuff is a bit crazy here with the UM2 around the corner)

**Comment by nallath** [comment] 2014-03-04 09:38
@daid; Is this fixed?

**Comment by daid** [comment] 2014-05-26 10:08
Should be fixed in latest versions.

**Closed as completed by daid** 2014-05-26 10:08 UTC
Labels: Bug, Linux
