### ISSUE TITLE
Mac version not slicing

### ISSUE THREAD

**Issue by kazzaqov** [daid/LegacyCura#503] opened 2013-07-17 17:56 UTC
Lots of people seem to have this problem. Cura just does not slice objects and the save to toolpath button is unavaible. I have this bug since 13.05.3 or something. After closing Cura it shows a message that Cura has instantly stopped working and asking if I want to write a report. Slice log is empty.

**Comment by daid** [comment] 2013-07-24 11:39
Reporting it again doesn't help the issue one bit. Duplicate of... few other issues.

**Closed as completed by daid** 2013-07-24 11:39 UTC
