### ISSUE TITLE
Is there an ability to use EngineResult methods to add additional information into GCode?

### ISSUE THREAD

**Issue by RaD** [daid/LegacyCura#850] opened 2014-05-26 11:12 UTC
For example I need to have in GCode file the information of these methods: `getPrintTime()`, `getFilamentWeight()`. I can make simple patch for Ubuntu version of Cura but how to do this for Windows?

Can you implement this ability for Windows version?
Or just tell me how to build this repo on Windows?
Thanks.

**Comment by RaD** [comment] 2014-05-26 11:25
I see the following at the beginning of GCode file:

```
;Print time: #P_TIME#
;Filament used: #F_AMNT#m #F_WGHT#g
;Filament cost: #F_COST#
```

**Comment by RaD** [comment] 2014-05-26 11:34
Also, why doesn't method `replaceGCodeTags()` used in Cura?

**Comment by mpatoulachik** [comment] 2014-07-05 21:02
This was already pointed in issue #459, fixed by patch #632 and then closed.
Also pointed in #831 (closed) that the method call was removed.
The problem is still here in Cura 14.07

**Comment by pmsimard** [comment] 2015-01-08 18:16
This is still happening in 14.12. as mentioned about the replaceGCodeTags() call in profile.py would resolve the issue but is never called. It could be called before triggering the postprocess plugins.

Occur in reprap with the default start.gcode. Doesn't occur in Ultigcode.

**Comment by daid** [comment] 2015-01-12 10:20
Should be fixed for next version.

**Closed as completed by daid** 2015-01-12 10:20 UTC
