### ISSUE TITLE
Unable to open Skeinforge settings from Pronterface

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#4] opened 2012-03-11 22:41 UTC
Running a build from my fork (which is your fork merged with bbum's) I get the following error when selecting SkeinPyPy->Change Settings... in Pronterface:

/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/Applications/SkeinPyPy/skeinforge_application/skeinforge.py': [Errno 2] No such file or directory

Since my application is located at "/Applications/osx64-SkeinPyPy-NewUI-Beta4" it looks like the path to Skeinforge may currently be absolute instead of relative.

**Comment by daid** [comment] 2012-03-12 11:37
the problem is that it's looking for "skeinforge_application/skeinforge.py" while the file has been renamed to "skeinpypy.py"
I've updated my fork of printrun to match the new file.
Rerunning the build.sh should fetch the new version.

**Comment by RedwoodForest** [comment] 2012-03-13 04:11
This is not fixed.

Here is the error message:
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/Applications/SkeinPyPy/skeinpypy.py': [Errno 2] No such file or directory

On my machine this file is located at "/Applications/SkeinPyPy/SkeinPyPy/skeinpypy.py" (note the additional SkeinPyPy).

On my machine I have renamed the folder named "osx64-SkeinPyPy-NewUI-Beta4" that the build script creates to "SkeinPyPy" and placed it in /Applications, resulting in the path above.

**Comment by RedwoodForest** [comment] 2012-03-13 06:52
Fixed in a fork and sent pull request: https://github.com/daid/Printrun/pull/1

**Comment by daid** [comment] 2012-03-13 10:12
Merged the pull request. It also contained the MacOS UI fix by BBum, but that's good :)

The plan is to get rid of PrintRun anyhow (OMG?!?). I understand why it works stable, unlike some other solutions. And I have some "SkeinPyPy" like ideas for the interface. But this new printer control won't be done soon. So Pronterface is to stay for now.

**Closed as completed by daid** 2012-03-13 10:12 UTC

**Comment by RedwoodForest** [comment] 2012-03-13 16:37
Whoops, still getting used to Git. I was intending to send a separate request for that one. Glad you were happy to integrate it.

I like the idea of a SkeinPyPyified printing interface.
