### ISSUE TITLE
Pause while printing

### ISSUE THREAD

**Issue by szelesi** [daid/LegacyCura#767] opened 2014-03-06 08:18 UTC
This happens in both SD card and USB mode, generate code very easy then I will start a print using RepRap/Marlin type machine and at any point it will pause and go to pause position, pressing resume in windows or button on my LCD box resumes but from then on the print is ruined as it un-pauses in the wrong place by a couple of steps. this can happen at any point in the print.
there seems to be no logic in the stop and the Gcode shows nothing, log als shows nothing about why it stops.

Any help would be great as this is becoming unusable for anything I have to leave alone.

Thanks

**Comment by szelesi** [comment] 2014-03-06 08:24
As a note Repetier will print ok but I don't want to use Repetier as I prefer Cura, this is why I am posting here and not on my printer forum, only Cura has this problem for me.

**Comment by nallath** [comment] 2014-03-06 10:03
This is done with the USB interface right? If so; its a duplicate of #480.

The USB interface does not get a lot of love from us, as relatively few people use it these days. In almost all cases it's better to use a controller for your printer.

**Comment by szelesi** [comment] 2014-03-06 10:34
Thanks for the reply
No, this is also when using standalone controller, I was running Gcode from Cura on my printer using SD card last night and it did it again. I can input a signal and it restarts in the slightly wrong place  but it is using either USB or controller.

**Comment by nallath** [comment] 2014-03-06 11:20
Interesting. I assume you've confirmed that this has nothing to do with backlash?

**Comment by szelesi** [comment] 2014-03-06 11:33
Backlash? if you mean vibration I am running at 40mm for some of the work to make sure I don't get it, like I said if I use Repetier it does not happen, only with Cura 14.01. really puzzling me

**Comment by nallath** [comment] 2014-03-06 12:03
Could you try it with 14.02 RC 5 aswell?

**Comment by szelesi** [comment] 2014-03-06 12:33
if you could please point me to a link I will gladly see if it repeats.

thanks for help

**Comment by nallath** [comment] 2014-03-06 13:31
http://software.ultimaker.com/Cura_closed_beta/

**Comment by szelesi** [comment] 2014-03-07 09:16
I ran a good long job last night and this seems to run all through with no issues, one point is the retraction did not work and I ended up with lots of string across the open areas of the print, not a problem as just clean-up, this was with combing off, now trying the same print with combing on to see if this makes a difference. thanks for the help.

**Comment by daid** [comment] 2014-03-07 10:22
For the retraction, it's most likely the minimal-extrusion-before-retraction setting which prevents some retraction.

(Closing this as you state the problem no longer happened)

**Closed as completed by daid** 2014-03-07 10:22 UTC
Labels: Bug
